//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Platillos
    {
        public int idPlatillo { get; set; }
        public string Nombre { get; set; }
        public int idEstado { get; set; }
        public int idCategoria { get; set; }
        public decimal Costo { get; set; }

        [JsonIgnore]
        public virtual Categorias Categorias { get; set; }
        [JsonIgnore]
        public virtual Estados Estados { get; set; }
    }
}
